### ISSUE TITLE
Frequency of data collection and export

### ISSUE THREAD

**Issue by NilX-20** [yizhiweimengxiangfendoudefeifei/Logitech_G29_readData#2]
May I ask a question? How often does your code get the data collected? Could it be exported to excel with time? Because I want to use it to record the data in  a period. Thanks a lot!

**Comment by yizhiweimengxiangfendoudefeifei** [comment]
或许可以写个函数写入到文本中，频率我没测试过

**Comment by yizhiweimengxiangfendoudefeifei** [comment]
> May I ask a question? How often does your code get the data collected? Could it be exported to excel with time? Because I want to use it to record the data in a period. Thanks a lot!

或许可以写个函数写入到文本中，频率我没测试过

**Comment by NilX-20** [comment]
好的，非常感谢您，请问您这边接受有偿开发吗？

**Comment by NilX-20** [comment]
非常感谢您！冒昧地请问一下您，您这边能够有时间接受有偿开发吗？
