### ISSUE TITLE
Hello, can you give an example of reading g923?

### ISSUE THREAD

**Issue by Canees** [yizhiweimengxiangfendoudefeifei/Logitech_G29_readData#3]
rt

**Comment by yizhiweimengxiangfendoudefeifei** [comment]
you can get it in the .docx.



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/28/2023 15:16 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | [yizhiweimengxiangfendoudefeifei/Logitech_G29_readData] Hello, can you give an example of reading g923? (Issue #3) |

rt
